### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by ichiriac** [jj101k/php-lint#1]
Hi @jj101k,

Wanted to know if you plan to continue or distribute it via npm/grunt/gulp ? If so I would like to contribute in order to package it if you are interested.

Note, as lint in PHP is just syntax validation, I've launched another project here : https://github.com/glayzzle/code-sniper - in order to check (as you have done here) some rules.

You are also welcomed if you want to contribute on code-sniper project.

BR,
Ioan

**Comment by jj101k** [comment]
Honestly, it's not a big enough priority to make progress right now, and certainly not worth publishing via NPM in its current state. The roadmap I had in mind was something like:

1. Detect variable name typos/missing "use" clauses and similar errors (done, but needs improvement)
2. Detect uses of undeclared properties or non-existent methods on $this
3. Detect mismatches between (inferred) variable type and function argument "type hint" where present; detect uses of undeclared properties or non-existent methods on most variables

Properly building class signatures (putting aside classes which use __get/__set/__call) requires at least some emulation of Composer's autoload behaviour, and type-related checking (aside from $this) requires type inference, neither of which I have time to build right now.

You are of course welcome to fork or grab bits of code which seem useful to you.
